services:
  app:
    build: ./services/app
    container_name: app-services
    ports:
      - "4002:4002"
    environment:
      - DATABASE_URL=postgresql://postgres:CvZ88u4sswM7fMfP@db.ojpvdsgpxvduovlamjto.supabase.co:5432/postgres
  user:
    build: ./services/users
    container_name: user-services
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=mongodb+srv://ciptandaru:Mo06SpC0bmoTT1O3@cluster0.p2nushc.mongodb.net/?retryWrites=true&w=majority
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "80:4000"
    environment:
      - APP_SERVICE_URL=http://app:4002
      - USER_SERVICE_URL=http://app:4001
